# Generated by Django 5.1 on 2024-09-02 17:16

from django.db import migrations


def initial_role_data(apps, schema_editor):
    Role = apps.get_model('api', 'Role')

    roles = [
        {'id': 0, 'name': 'Admin'},
        {'id': 1, 'name': 'User'},
        {'id': 2, 'name': 'Owner'},
        {'id': 3, 'name': 'Employee'},
    ]

    for role in roles:
        Role.objects.create(
            id=role['id'],
            name=role['name'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_role_data),
    ]

