# Generated by Django 5.1 on 2024-09-02 17:17

from django.db import migrations


def initial_user_data(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.create_superuser(
        username='admin',
        password='123',
        email='admin@example.com'
    )

    # Danh sách người dùng
    user = [
        {'first_name': 'Thành', 'last_name': 'Tâm', 'username': 'thangtam', 'role_id': 1, 'password': 'Thangtam@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Boy_1.jpg'},
        {'first_name': 'Bảo', 'last_name': 'Hưng', 'username': 'baohung', 'role_id': 1, 'password': 'Baohung@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Boy_1.jpg'},
        {'first_name': 'Linh', 'last_name': 'Mai', 'username': 'linhmai', 'role_id': 1, 'password': 'Linhmai@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Girl_1.jpg'},
    ]

    # Danh sách chủ sở hữu
    owner = [
        {'first_name': 'Anh', 'last_name': 'Phúc', 'username': 'anhphuc', 'role_id': 2, 'password': 'Anhphuc@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Boy_1.jpg'},
        {'first_name': 'Hương', 'last_name': 'Quyên', 'username': 'huongquyen', 'role_id': 2,
         'password': 'Huongquyen@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Girl_1.jpg'},
        {'first_name': 'Long', 'last_name': 'Khôi', 'username': 'longkhoi', 'role_id': 2, 'password': 'Longkhoi@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Boy_1.jpg'},
        {'first_name': 'Yến', 'last_name': 'Mai', 'username': 'yenmai', 'role_id': 2, 'password': 'Yenmai@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Girl_1.jpg'},
        {'first_name': 'Khoa', 'last_name': 'Hòa', 'username': 'khoahoa', 'role_id': 2, 'password': 'Khoahoa@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Boy_1.jpg'},
    ]

    # Danh sách nhân viên
    employee = [
        {'first_name': 'Mỹ', 'last_name': 'Phương', 'username': 'myphuong', 'role_id': 3, 'password': 'Myphuong@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Girl_1.jpg'},
        {'first_name': 'Như', 'last_name': 'Anh', 'username': 'nhuanh', 'role_id': 3, 'password': 'Nhuanh@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Girl_1.jpg'},
        {'first_name': 'Nam', 'last_name': 'Tú', 'username': 'namtu', 'role_id': 3, 'password': 'Namtu@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Boy_1.jpg'},
        {'first_name': 'Thu', 'last_name': 'Hương', 'username': 'thuhuong', 'role_id': 3, 'password': 'Thuhuong@123',
         'avatar': 'https://res.cloudinary.com/dhitdivyi/image/upload/v1726756063/Avatar_Profile_Girl_1.jpg'},
    ]

    users = user + owner + employee

    for user in users:
        User.objects.create_user(
            first_name=user['first_name'],
            last_name=user['last_name'],
            username=user['username'],
            password=user['password'],
            role_id=user['role_id'],
            phone_number='0351234567',
            avatar=user['avatar']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_data'),
    ]

    operations = [
        migrations.RunPython(initial_user_data)
    ]

