# Generated by Django 5.1 on 2024-09-02 17:18

from django.db import migrations


def initial_category_data(apps, schema_editor):
    RestaurantCategory = apps.get_model('api', 'RestaurantCategory')
    FoodCategory = apps.get_model('api', 'FoodCategory')

    restaurantCategories = [
        {'name': 'Nướng'},
        {'name': 'Lẩu'},
        {'name': 'Chay'},
        {'name': 'Hải sản'},
        {'name': 'Đồ ăn nhanh'},
    ]

    for restaurantCategory in restaurantCategories:
        RestaurantCategory.objects.create(
            name=restaurantCategory['name']
        )

    # Danh mục món ăn quán Nướng
    FoodCategory.objects.create(name='Rau củ')
    FoodCategory.objects.create(name='Hải sản')
    FoodCategory.objects.create(name='Thịt')

    # Danh mục món ăn quán Lẩu
    FoodCategory.objects.create(name='Nước lẩu')
    # FoodCategory.objects.create(name='Thịt')
    # FoodCategory.objects.create(name='Hải sản')

    # Danh mục món ăn quán Chay
    # FoodCategory.objects.create(name='Rau củ')
    FoodCategory.objects.create(name='Canh')
    FoodCategory.objects.create(name='Thịt chay')

    # Danh mục món ăn quán Hải sản
    FoodCategory.objects.create(name='Tôm')
    FoodCategory.objects.create(name='Cua')
    FoodCategory.objects.create(name='Cá')

    # Danh mục món ăn quán Đồ ăn nhanh
    FoodCategory.objects.create(name='Burger')
    FoodCategory.objects.create(name='Trà sữa')
    FoodCategory.objects.create(name='Gà rán')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_data'),
    ]

    operations = [
        migrations.RunPython(initial_category_data)
    ]
