# Generated by Django 5.1 on 2024-09-02 17:19

from django.db import migrations
import random


def initial_food_data(apps, schema_editor):
    Food = apps.get_model('api', 'Food')

    # Nướng: 1, Lẩu: 2, Chay: 3, Hải sản: 4, Đồ ăn nhanh: 5

    # Rau củ: 1, Hải sản: 2, Thịt: 3, Nước lẩu: 4, Canh: 5, Thịt chay: 6, Tôm: 7, Cua: 8, Cá: 9, Burger: 10, Trà sữa: 11
    # Gà rán: 12

    foods = [
        # Nhà hàng Nướng Ngon: 1
        # Danh mục 'Rau củ'
        {'name': 'Đậu bắp nướng', 'price': 50000.0, 'description': 'Đậu bắp tươi nướng muối ớt',
         'category': 1, 'restaurant_id': 1},
        {'name': 'Ngô nướng', 'price': 40000.0, 'description': 'Ngô ngọt nướng bơ tỏi', 'category': 1,
         'restaurant_id': 1},

        # Danh mục 'Hải sản'
        {'name': 'Tôm nướng', 'price': 100000.0, 'description': 'Tôm nướng muối ớt', 'category': 2,
         'restaurant_id': 1},
        {'name': 'Mực nướng', 'price': 120000.0, 'description': 'Mực nướng sa tế', 'category': 2,
         'restaurant_id': 1},

        # Danh mục 'Thịt'
        {'name': 'Sườn nướng BBQ', 'price': 150000.0, 'description': 'Sườn nướng BBQ đậm đà', 'category': 3,
         'restaurant_id': 1},
        {'name': 'Bò nướng', 'price': 160000.0, 'description': 'Bò nướng tiêu xanh', 'category': 3,
         'restaurant_id': 1},

        # Lẩu Đại Hỷ: 2
        # Món ăn cho danh mục 'Nước lẩu'
        {'name': 'Nước lẩu Thái', 'price': 120000.0, 'description': 'Nước lẩu Thái chua cay, đầy hương vị',
         'category': 4, 'restaurant_id': 2},
        {'name': 'Nước lẩu Tứ Xuyên', 'price': 130000.0, 'description': 'Nước lẩu Tứ Xuyên cay nồng, đặc trưng',
         'category': 4, 'restaurant_id': 2},

        # Món ăn cho danh mục 'Thịt'
        {'name': 'Sườn heo', 'price': 150000.0, 'description': 'Sườn heo tươi ngon, dùng cho lẩu',
         'category': 3, 'restaurant_id': 2},
        {'name': 'Thịt bò', 'price': 160000.0, 'description': 'Thịt bò tươi, thái lát mỏng cho lẩu',
         'category': 3, 'restaurant_id': 2},

        # Món ăn cho danh mục 'Hải sản'
        {'name': 'Tôm sú', 'price': 100000.0, 'description': 'Tôm sú tươi ngon, dùng cho lẩu',
         'category': 2, 'restaurant_id': 2},
        {'name': 'Mực ống', 'price': 120000.0, 'description': 'Mực ống tươi, thích hợp cho lẩu',
         'category': 2, 'restaurant_id': 2},

        # Chay Thanh Tịnh: 3
        # Món ăn cho danh mục 'Rau củ'
        {'name': 'Rau muống xào', 'price': 40000.0, 'description': 'Rau muống xào tỏi thơm ngon',
         'category': 1, 'restaurant_id': 3},
        {'name': 'Đậu phụ xào rau củ', 'price': 45000.0, 'description': 'Đậu phụ xào với nhiều loại rau củ tươi',
         'category': 1, 'restaurant_id': 3},

        # Món ăn cho danh mục 'Canh'
        {'name': 'Canh bí đỏ', 'price': 50000.0, 'description': 'Canh bí đỏ nấu thanh mát', 'category': 5,
         'restaurant_id': 3},
        {'name': 'Canh chua chay', 'price': 55000.0, 'description': 'Canh chua chay với nhiều loại rau củ và nấm',
         'category': 5, 'restaurant_id': 3},

        # Món ăn cho danh mục 'Thịt chay'
        {'name': 'Thịt chay nướng', 'price': 60000.0, 'description': 'Thịt chay nướng đậm đà gia vị',
         'category': 6, 'restaurant_id': 3},
        {'name': 'Sườn chay xào sả ớt', 'price': 65000.0, 'description': 'Sườn chay xào sả ớt cay nồng',
         'category': 6, 'restaurant_id': 3},

        # Hải sải biển xanh: 4
        # Món ăn cho danh mục 'Tôm'
        {'name': 'Tôm sú nướng', 'price': 120000.0, 'description': 'Tôm sú nướng thơm ngon', 'category': 7,
         'restaurant_id': 4},
        {'name': 'Tôm rang me', 'price': 130000.0, 'description': 'Tôm rang me chua ngọt', 'category': 7,
         'restaurant_id': 4},

        # Món ăn cho danh mục 'Cua'
        {'name': 'Cua sốt ớt', 'price': 150000.0, 'description': 'Cua sốt ớt cay nồng', 'category': 8,
         'restaurant_id': 4},
        {'name': 'Cua rang muối', 'price': 160000.0, 'description': 'Cua rang muối thơm ngon', 'category': 8,
         'restaurant_id': 4},

        # Món ăn cho danh mục 'Cá'
        {'name': 'Cá lóc nướng', 'price': 140000.0, 'description': 'Cá lóc nướng thơm ngon', 'category': 9,
         'restaurant_id': 4},
        {'name': 'Cá chiên xù', 'price': 130000.0, 'description': 'Cá chiên xù giòn rụm', 'category': 9,
         'restaurant_id': 4},

        # Đồ ăn nhanh 24: 5
        # Món ăn cho danh mục 'Burger'
        {'name': 'Burger phô mai', 'price': 80000.0, 'description': 'Burger với phô mai tan chảy',
         'category': 10, 'restaurant_id': 5},
        {'name': 'Burger bò nướng', 'price': 90000.0, 'description': 'Burger với thịt bò nướng',
         'category': 10, 'restaurant_id': 5},

        # Món ăn cho danh mục 'Trà sữa'
        {'name': 'Trà sữa truyền thống', 'price': 50000.0, 'description': 'Trà sữa truyền thống ngọt ngào',
         'category': 11, 'restaurant_id': 5},
        {'name': 'Trà sữa matcha', 'price': 55000.0, 'description': 'Trà sữa matcha thơm ngon',
         'category': 11, 'restaurant_id': 5},

        # Món ăn cho danh mục 'Gà rán'
        {'name': 'Gà rán giòn', 'price': 70000.0, 'description': 'Gà rán giòn rụm', 'category': 12,
         'restaurant_id': 5},
        {'name': 'Gà rán mật ong', 'price': 75000.0, 'description': 'Gà rán với sốt mật ong ngọt ngào',
         'category': 12, 'restaurant_id': 5}
    ]

    for food in foods:
        Food.objects.create(
            name=food['name'],
            price=food['price'],
            discount=random.randint(0, 20000),
            description=food['description'],
            category_id=food['category'],
            rating=0,
            restaurant_id=food['restaurant_id'],
            image='https://res.cloudinary.com/dhitdivyi/image/upload/v1725474107/m82nkwmtg5x7hh2uny7q.jpg',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurant_data'),
    ]

    operations = [
        migrations.RunPython(initial_food_data)
    ]

