# Generated by Django 5.1 on 2024-09-02 17:19

import random

from django.db import migrations


def initial_cart_data(apps, schema_editor):
    Cart = apps.get_model('api', 'Cart')

    # Nướng: 1, Lẩu: 2, Chay: 3, Hải sản: 4, Đồ ăn nhanh: 5

    carts = [
        {'note': 'Đảm bảo nướng vừa tới, không quá cháy', 'restaurant_id': 1},
        {'note': 'Giao lẩu với nước lẩu Thái, không để nguội', 'restaurant_id': 2},
        {'note': 'Đảm bảo rau củ và đậu phụ không bị nát', 'restaurant_id': 3},
        {'note': 'Giao tôm và cua tươi, không để đông đá', 'restaurant_id': 4},
        {'note': 'Burger cần được đóng gói cẩn thận để không bị nhão', 'restaurant_id': 5},
        {'note': 'Nước lẩu Tứ Xuyên cần phải giữ ấm, không để nguội', 'restaurant_id': 2},
        {'note': 'Gà rán phải giòn, không bị ướt', 'restaurant_id': 5},
        {'note': 'Thịt bò nướng cần được giữ ấm, không bị khô', 'restaurant_id': 1},
        {'note': 'Tôm sú nướng cần giữ độ tươi ngon, không bị khô', 'restaurant_id': 4},
        {'note': 'Canh bí đỏ cần giữ nóng, không bị nguội', 'restaurant_id': 3}
    ]

    for cart in carts:
        Cart.objects.create(
            note=cart['note'],
            status=random.randint(0, 1),
            user_id=random.randint(2, 13),
            restaurant_id=cart['restaurant_id'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_food_data'),
    ]

    operations = [
        migrations.RunPython(initial_cart_data)
    ]

