# Generated by Django 5.1 on 2024-09-02 17:20

from django.db import migrations

from api.models import Food


def initial_cart_detail_data(apps, schema_editor):
    CartDetail = apps.get_model('api', 'CartDetail')

    # Danh sách chi tiết các cart
    cart_details = [
        # Cart 1: Nhà hàng Nướng Ngon
        [
            {'cart_id': 1, 'food_id': 1, 'quantity': 1},  # Đậu bắp nướng
            {'cart_id': 1, 'food_id': 2, 'quantity': 2},  # Ngô nướng
            {'cart_id': 1, 'food_id': 3, 'quantity': 1},  # Tôm nướng
            {'cart_id': 1, 'food_id': 4, 'quantity': 1},  # Mực nướng
            {'cart_id': 1, 'food_id': 5, 'quantity': 1}  # Sườn nướng BBQ
        ],
        # Cart 2: Lẩu Đại Hỷ
        [
            {'cart_id': 2, 'food_id': 6, 'quantity': 1},  # Nước lẩu Thái
            {'cart_id': 2, 'food_id': 7, 'quantity': 1},  # Nước lẩu Tứ Xuyên
            {'cart_id': 2, 'food_id': 8, 'quantity': 1},  # Sườn heo
            {'cart_id': 2, 'food_id': 9, 'quantity': 1},  # Thịt bò
            {'cart_id': 2, 'food_id': 10, 'quantity': 2},  # Tôm sú
            {'cart_id': 2, 'food_id': 11, 'quantity': 1}  # Mực ống
        ],
        # Cart 3: Chay Thanh Tịnh
        [
            {'cart_id': 3, 'food_id': 12, 'quantity': 2},  # Rau muống xào
            {'cart_id': 3, 'food_id': 13, 'quantity': 1},  # Đậu phụ xào rau củ
            {'cart_id': 3, 'food_id': 14, 'quantity': 1},  # Canh bí đỏ
            {'cart_id': 3, 'food_id': 15, 'quantity': 1},  # Canh chua chay
            {'cart_id': 3, 'food_id': 16, 'quantity': 1},  # Thịt chay nướng
            {'cart_id': 3, 'food_id': 17, 'quantity': 1}  # Sườn chay xào sả ớt
        ],
        # Cart 4: Hải Sản Biển Xanh
        [
            {'cart_id': 4, 'food_id': 18, 'quantity': 1},  # Tôm sú nướng
            {'cart_id': 4, 'food_id': 19, 'quantity': 1},  # Tôm rang me
            {'cart_id': 4, 'food_id': 20, 'quantity': 1},  # Cua sốt ớt
            {'cart_id': 4, 'food_id': 21, 'quantity': 1},  # Cua rang muối
            {'cart_id': 4, 'food_id': 22, 'quantity': 1},  # Cá lóc nướng
            {'cart_id': 4, 'food_id': 23, 'quantity': 1}  # Cá chiên xù
        ],
        # Cart 5: Đồ Ăn Nhanh 24
        [
            {'cart_id': 5, 'food_id': 24, 'quantity': 1},  # Burger phô mai
            {'cart_id': 5, 'food_id': 25, 'quantity': 1},  # Burger bò nướng
            {'cart_id': 5, 'food_id': 26, 'quantity': 1},  # Trà sữa truyền thống
            {'cart_id': 5, 'food_id': 27, 'quantity': 1},  # Trà sữa matcha
            {'cart_id': 5, 'food_id': 28, 'quantity': 1},  # Gà rán giòn
            {'cart_id': 5, 'food_id': 29, 'quantity': 1}  # Gà rán mật ong
        ],
        # Cart 6: Giao lẩu với nước lẩu Tứ Xuyên
        [
            {'cart_id': 6, 'food_id': 7, 'quantity': 2},  # Nước lẩu Tứ Xuyên
            {'cart_id': 6, 'food_id': 8, 'quantity': 1},  # Sườn heo
            {'cart_id': 6, 'food_id': 9, 'quantity': 1},  # Thịt bò
            {'cart_id': 6, 'food_id': 10, 'quantity': 1},  # Tôm sú
            {'cart_id': 6, 'food_id': 11, 'quantity': 1}  # Mực ống
        ],
        # Cart 7: Gà rán phải giòn
        [
            {'cart_id': 7, 'food_id': 28, 'quantity': 2},  # Gà rán giòn
            {'cart_id': 7, 'food_id': 29, 'quantity': 1}  # Gà rán mật ong
        ],
        # Cart 8: Thịt bò nướng cần giữ ấm
        [
            {'cart_id': 8, 'food_id': 3, 'quantity': 1},  # Sườn nướng BBQ
            {'cart_id': 8, 'food_id': 4, 'quantity': 1},  # Bò nướng
            {'cart_id': 8, 'food_id': 1, 'quantity': 1}  # Đậu bắp nướng
        ],
        # Cart 9: Tôm sú nướng cần giữ tươi
        [
            {'cart_id': 9, 'food_id': 18, 'quantity': 2},  # Tôm sú nướng
            {'cart_id': 9, 'food_id': 19, 'quantity': 1}  # Tôm rang me
        ],
        # Cart 10: Canh bí đỏ cần giữ nóng
        [
            {'cart_id': 10, 'food_id': 14, 'quantity': 2},  # Canh bí đỏ
            {'cart_id': 10, 'food_id': 15, 'quantity': 1}  # Canh chua chay
        ]
    ]

    # Lưu chi tiết các cart vào cơ sở dữ liệu
    for cart_detail_list in cart_details:
        for cart_detail in cart_detail_list:
            food = Food.objects.get(pk=cart_detail['food_id'])
            CartDetail.objects.create(
                cart_id=cart_detail['cart_id'],
                food_id=cart_detail['food_id'],
                quantity=cart_detail['quantity'],
                amount=food.price * cart_detail['quantity'] - food.discount
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cart_data'),
    ]

    operations = [
        migrations.RunPython(initial_cart_detail_data)
    ]
