# Generated by Django 5.1 on 2024-09-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_detail_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Bank'), (2, 'E-Wallet')], default=0),
        ),
    ]
