# Generated by Django 5.1 on 2024-09-09 03:31

from django.db import migrations

from api.models import Cart


def initial_payment_data(apps, schema_editor):
    Payment = apps.get_model('api', 'Payment')
    payments = [
        {'cart_id': 1, 'status': 0, 'method': 0, 'note': 'Thanh toán đơn hàng 1'},
        {'cart_id': 2, 'status': 1, 'method': 1, 'note': 'Thanh toán đơn hàng 2'},
        {'cart_id': 3, 'status': 2, 'method': 2, 'note': 'Thanh toán đơn hàng 3'},
        {'cart_id': 4, 'status': 3, 'method': 0, 'note': 'Thanh toán đơn hàng 4'},
        {'cart_id': 5, 'status': 4, 'method': 1, 'note': 'Thanh toán đơn hàng 5'},
        {'cart_id': 6, 'status': 0, 'method': 2, 'note': 'Thanh toán đơn hàng 6'},
        {'cart_id': 7, 'status': 1, 'method': 0, 'note': 'Thanh toán đơn hàng 7'},
        {'cart_id': 8, 'status': 2, 'method': 1, 'note': 'Thanh toán đơn hàng 8'},
        {'cart_id': 9, 'status': 3, 'method': 2, 'note': 'Thanh toán đơn hàng 9'},
        {'cart_id': 10, 'status': 4, 'method': 0, 'note': 'Thanh toán đơn hàng 10'},
    ]

    for payment in payments:
        Payment.objects.create(
            cart_id=payment['cart_id'],
            status=payment['status'],
            method=payment['method'],
            note=payment['note'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_payment_method'),
    ]

    operations = [
        migrations.RunPython(initial_payment_data)
    ]
